#!/bin/bash

arch=${1:-rv32im}

if [[ $arch =~ ^rv(32|64)((i?m?a?f?d?|g?)c?)(s?u?)$ ]]; then
    xlen=${BASH_REMATCH[1]}
    isa=${BASH_REMATCH[2]}
    priv=${BASH_REMATCH[4]}
    if [[ $isa =~ ^(.*)g(.*)$ ]]; then
	isa=${BASH_REMATCH[1]}imafd${BASH_REMATCH[2]}
    fi
    if [[ $priv =~ s ]]; then
	env="p v"
    else
	env="p"
    fi
else
    echo "ERROR: unknown or unsupported architecture ($arch)" >&2
    exit 1
fi

test_dir=`dirname $0`/../../riscv-tests

for e in $env; do
    #echo "# for e = $e"
    for f in `ls $test_dir/isa/rv$xlen[m$priv][$isa]-$e-* | grep -vE ".dump$" | sort`; do
       echo "$f"
    done

    echo
done

