# -*- gdb-script -*-
# this file was automatically generated by gen-test-all
# for architecture rv64imacu

set remotetimeout 5000
set remotelogfile gdb-remote.log
set logging overwrite
set logging file gdb-client.log
set logging on
set pagination off

target remote | openocd --debug --log_output openocd.log --command "gdb_port pipe" --file ./testing/scripts/../targets/ssith_gfe.cfg

define run_prog
  dont-repeat

  monitor reset halt

  delete
  printf "Loading $arg0\n"
  file $arg0
  load

  break exit
  commands
    info registers
  end

  continue

end

define run_test_p
  dont-repeat

  monitor reset halt

  delete
  printf "Loading $arg0\n"
  file $arg0
  load


  break write_tohost
  commands
    if $gp == 1
      printf "PASS\n"
    else
      printf "FAIL (tohost=%x)\n", $gp
    end
  end

  continue

end

define run_test_v
  dont-repeat

  monitor reset halt

  delete
  printf "Loading $arg0\n"
  file $arg0
  load

  break terminate
  commands
    if $a0 == 1
      printf "PASS\n"
    else
      printf "FAIL (tohost=%x)\n", $a0
    end
  end

  continue

  if $a0 == 1
    printf "PASS\n"
  else
    printf "FAIL (tohost=%x)\n", $a0
  end

end

run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ua-p-amoadd_d
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ua-p-amoadd_w
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ua-p-amoand_d
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ua-p-amoand_w
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ua-p-amomax_d
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ua-p-amomaxu_d
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ua-p-amomaxu_w
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ua-p-amomax_w
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ua-p-amomin_d
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ua-p-amominu_d
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ua-p-amominu_w
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ua-p-amomin_w
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ua-p-amoor_d
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ua-p-amoor_w
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ua-p-amoswap_d
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ua-p-amoswap_w
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ua-p-amoxor_d
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ua-p-amoxor_w
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64mi-p-access
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64mi-p-breakpoint
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64mi-p-csr
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64mi-p-illegal
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64mi-p-ma_addr
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64mi-p-ma_fetch
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64mi-p-mcsr
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64mi-p-sbreak
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64mi-p-scall
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ua-p-lrsc
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64uc-p-rvc
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-add
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-addi
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-addiw
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-addw
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-and
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-andi
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-auipc
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-beq
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-bge
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-bgeu
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-blt
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-bltu
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-bne
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-fence_i
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-jal
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-jalr
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-lb
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-lbu
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-ld
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-lh
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-lhu
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-lui
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-lw
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-lwu
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-or
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-ori
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-sb
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-sd
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-sh
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-simple
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-sll
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-slli
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-slliw
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-sllw
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-slt
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-slti
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-sltiu
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-sltu
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-sra
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-srai
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-sraiw
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-sraw
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-srl
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-srli
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-srliw
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-srlw
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-sub
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-subw
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-sw
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-xor
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64ui-p-xori
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64um-p-div
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64um-p-divu
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64um-p-divuw
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64um-p-divw
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64um-p-mul
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64um-p-mulh
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64um-p-mulhsu
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64um-p-mulhu
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64um-p-mulw
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64um-p-rem
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64um-p-remu
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64um-p-remuw
run_test_p ./testing/scripts/../../riscv-tools/riscv-tests/isa/rv64um-p-remw

disconnect
quit
