//
// Generated by Bluespec Compiler, version 2017.07.A (build e1df8052c, 2017-07-21)
//
//
//
//
// Ports:
// Name                         I/O  size props
// axi_in_tready                  O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// axi_in_tvalid                  I     1 unused
// axi_in_tdata                   I   608 unused
// axi_in_tstrb                   I    76 unused
// axi_in_tkeep                   I    76 unused
// axi_in_tlast                   I     1 unused
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkSVF_Bridge(CLK,
		    RST_N,

		    axi_in_tvalid,
		    axi_in_tdata,
		    axi_in_tstrb,
		    axi_in_tkeep,
		    axi_in_tlast,

		    axi_in_tready);
  input  CLK;
  input  RST_N;

  // action method axi_in_m_tvalid
  input  axi_in_tvalid;
  input  [607 : 0] axi_in_tdata;
  input  [75 : 0] axi_in_tstrb;
  input  [75 : 0] axi_in_tkeep;
  input  axi_in_tlast;

  // value method axi_in_m_tready
  output axi_in_tready;

  // signals for module outputs
  wire axi_in_tready;

  // rule scheduling signals
  wire CAN_FIRE_axi_in_m_tvalid, WILL_FIRE_axi_in_m_tvalid;

  // action method axi_in_m_tvalid
  assign CAN_FIRE_axi_in_m_tvalid = 1'd1 ;
  assign WILL_FIRE_axi_in_m_tvalid = 1'd1 ;

  // value method axi_in_m_tready
  assign axi_in_tready = 1'd1 ;
endmodule  // mkSVF_Bridge

