/*
 * Generated by Bluespec Compiler, version 2018.10.beta1 (build e1df8052c, 2018-10-17)
 * 
 * 
 * 
 */
#ifndef __vpi_wrapper_c_debug_client_connect_h__
#define __vpi_wrapper_c_debug_client_connect_h__

#include <vpi_user.h>

/* registration function */
void c_debug_client_connect_vpi_register();

/* VPI wrapper function */
PLI_INT32 c_debug_client_connect_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_c_debug_client_connect_h__ */
